version: '3.1'

services:

  postgres-14:
    container_name: postgres-14
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ../data/postgresql-14:/var/lib/postgresql/data
